- name: Install WebApp on Windows
  hosts: windows
  tasks:
    - name: Install git
      win_chocolatey:
        name: git
        state: latest
    - name: Install NodeJS
      win_chocolatey:
        name: NodeJS
        state: latest
    - name: Install Docker Desktop
      win_chocolatey:
        name: docker-desktop
        state: present
    - name: Create Folder for WebApp
      win_file:
        path: C:\repos\newWebApp
        state: directory
    - name: Pull Git Repository
      win_command: cmd.exe /c git clone https://github.com/loukleon2021/containerized-web-app.git C:\repos\newWebApp
    - name: Ensure Docker Desktop is up and running
      win_service:
        name: com.docker.service
        state: started
    - name: Start WebApp
      win_command: cmd.exe /c docker-compose -f c:\repos\newWebApp\docker-compose.yml up -d
